controller_list:
        - name: arm_position_controller
          action_ns: follow_joint_trajectory # namespace for ROS action server of controller
          type: FollowJointTrajectory
          joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
