# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: fanuc_crx10ial_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  gains:
          joint_1: {p: 100, i: 0.1, d: 10}
          joint_2: {p: 100, i: 0.1, d: 10}
          joint_3: {p: -100.0, i: -0.01, d: -10.0}
          joint_4: {p: 100, i: 0.1, d: 10}
          joint_5: {p: 100, i: 0.1, d: 10}
          joint_6: {p: 100, i: 0.1, d: 10}
