controller_list:
  - name: joint_trajectory_action 
    action_ns: "" 
    type: FollowJointTrajectory
    default: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
